layout_spectrum: 0.4510638
typography_spectrum: 0.1914894
color:
  lightness: 0.7152694
  brandStrength: 0.8565074
  saturation: 0.9723814
  rhythmicContrast: 0.4465774
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: OPMT
