layout_spectrum: 0.4510638
name: OPMT
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8565074
  lightness: 0.9808511
  saturation: 0.9723814
  rhythmicContrast: 0.4465774
  brandColors:
    - '#D6C6A3'
    - '#16171F'
    - '#C53980'
    - '#77E1B3'
    - '#4B535C'
typography_spectrum: 0.1914894
